python poetry run

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -18,7 +18,7 @@ jobs:
     timeout-minutes: 30
     env:
       ACTIONS_STEP_DEBUG: true
-      HOME: /home/runner
+      HOME: /home/github-runner
 
     steps:
       - name: Check out code
@@ -46,6 +46,11 @@ jobs:
           python3.13 -m poetry install --no-interaction --no-root
       - name: Install ncdump dependency
         run: sudo apt-get install netcdf-bin
+      - name: Debug venv location
+        run: |
+          python3.13 -m poetry env info
+          ls -la .
+          ls -la .venv/ || echo ".venv directory not found"
       - name: Install library
         run: python3.13 -m poetry install --no-interaction --with dev
       - name: Run tests
@@ -53,11 +58,10 @@ jobs:
           COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
           COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
         run: |
-          source .venv/bin/activate
           if [ "${{ matrix.coverage}}" == "fast-and-wo-coverage" ]; then
-            make run-quick-tests
+            python3.13 -m poetry run make run-quick-tests
           else
-            make run-tests
+            python3.13 -m poetry run make run-tests
           fi
       - name: Upload coverage reports to Codecov
         if: matrix.coverage == 'w-coverage'
